// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8KTQ8WlhT5xA-3H7gEmJfEMq0F8ZupE',
    appId: '1:922542220464:web:7741ec35004acdc6f50775',
    messagingSenderId: '922542220464',
    projectId: 'fir-38b88',
    authDomain: 'fir-38b88.firebaseapp.com',
    storageBucket: 'fir-38b88.firebasestorage.app',
    measurementId: 'G-CG29JDG6E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzv2VEVq_HzD39i_i06oshVGvXNBfFQAw',
    appId: '1:922542220464:android:f3fe36f13ca5bf11f50775',
    messagingSenderId: '922542220464',
    projectId: 'fir-38b88',
    storageBucket: 'fir-38b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuoSaYL47VoHiH8xYQavxBxO9BHKyzPkI',
    appId: '1:922542220464:ios:957b3b4b02f2c05af50775',
    messagingSenderId: '922542220464',
    projectId: 'fir-38b88',
    storageBucket: 'fir-38b88.firebasestorage.app',
    iosBundleId: 'com.secure.track.securetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuoSaYL47VoHiH8xYQavxBxO9BHKyzPkI',
    appId: '1:922542220464:ios:957b3b4b02f2c05af50775',
    messagingSenderId: '922542220464',
    projectId: 'fir-38b88',
    storageBucket: 'fir-38b88.firebasestorage.app',
    iosBundleId: 'com.secure.track.securetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK8KTQ8WlhT5xA-3H7gEmJfEMq0F8ZupE',
    appId: '1:922542220464:web:a8273561730d5217f50775',
    messagingSenderId: '922542220464',
    projectId: 'fir-38b88',
    authDomain: 'fir-38b88.firebaseapp.com',
    storageBucket: 'fir-38b88.firebasestorage.app',
    measurementId: 'G-C1TY8R2QNG',
  );
}
